# Generated by Django 4.0.3 on 2022-03-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_email_user_fullname_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='liked_songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(max_length=250)),
            ],
        ),
    ]
