# Generated by Django 4.0.3 on 2022-03-30 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_liked_songs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='liked_songs',
        ),
    ]
