# Generated by Django 4.0.3 on 2022-03-30 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_liked_songs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liked_songs',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.user', to_field='username'),
        ),
    ]
