# Generated by Django 4.0.3 on 2022-03-30 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_liked_songs_u_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liked_songs',
            old_name='u_name',
            new_name='username',
        ),
    ]
