# Generated by Django 4.0.3 on 2022-03-30 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_u_name_liked_songs_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='liked_songs',
        ),
    ]
