# Generated by Django 4.0.3 on 2022-03-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_liked_songs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liked_songs',
            name='track_id',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
