# Generated by Django 4.0.3 on 2022-03-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_liked_songs_track_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liked_songs',
            name='album_id',
            field=models.CharField(max_length=250),
        ),
    ]
